config/routes.rb
Rails.application.routes.draw do

  root 'front_page#main'

  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'resume' => 'pages#resume'

  resources :jobs
  resources :courses
  resources :projects
  resources :code_links

  if Rails.env.production?
    devise_for :users, controllers: { registrations: "registrations" }
  else
    devise_for :users
  end

  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "settings", :to => "devise/registrations#edit"
    get "logout",   :to => "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, presence: true
  validates :start_date, presence: true
  validates :location, presence: true
  validates :description, presence: true
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_job, only: [:show, :edit, :update, :destory]

  def show
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to jobs_path
    else
      render 'new'
    end
  end

  def index
    @jobs = Job.all
  end

  def edit
  end

  def update
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render 'edit'
    end
  end

  def destroy
    @job.destroy

    redirect_to jobs_path
  end

  private
  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :start_date, :end_date, :location, :description)
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_edit_icons.html.haml
- if user_signed_in?
  %section.edit-icons
    = link_to image_tag("icons/edit.png"), edit_job_path(job)
    = link_to image_tag("icons/delete.png"), job_path(job), method: :delete,
      data: { confirm: "Are you sure you want to delete job #{job.title}?" }

app/views/jobs/_form.html.haml
= simple_form_for @job do |f|

  .row
    .column.small-6
      = f.input :title
    .column.small-6
      = f.input :location
    .column.small-12
      = f.input :description
    .column.small-12
      = f.button :submit

app/views/jobs/_index.html.haml
%section.jobs-feed.index
  %ul
    - jobs.each do |job|
      %li
        = render "jobs/show", job: job
        .description
          :markdown
            #{job.description}
        = render "jobs/edit_icons", job: job

- if user_signed_in?
  = link_to "Add Job", new_job_path

app/views/jobs/_jobs_feed.html.haml
%section.jobs-feed
  %ul
    - jobs.each do |job|
      %li
        = render "jobs/show", job: job

- if user_signed_in?
  = link_to "Add Job", new_job_path

app/views/jobs/_show.html.haml
%article.job
  %h3 #{job.title} - #{job.location}
  - if user_signed_in?
    .icons.row
      = link_to edit_job_path(job), class: "column small-6" do
        %i.fi-pencil
      = link_to job_path(job), method: :delete, class: "column small-6",
        data: { confirm: "Are you sure you'd like to delete job '#{job.title}'?" } do
        %i.fi-trash
  .job-description
    :markdown
      #{job.description}

app/views/jobs/edit.html.haml
= render "form"

app/views/jobs/index.html.haml
- title = "Work Experience"
- description = "View my past work experience and positions."
- image = URI.join(root_url, image_path("favicon.png"))

- meta title: title, description: description,
  og: { title: title, description: description, image: image, url: request.original_url }

.left
  %h1 Work Experience

  = render "jobs/jobs_feed", jobs: @jobs

.right
  = link_to "Download PDF", "/resume.pdf", id: "resume-link"

app/views/jobs/new.html.haml
%h1 New Job

= render "form"