config/routes.rb
Rails.application.routes.draw do

  root 'front_page#main'

  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'resume' => 'pages#resume'

  resources :jobs
  resources :courses
  resources :projects
  resources :code_links

  if Rails.env.production?
    devise_for :users, controllers: { registrations: "registrations" }
  else
    devise_for :users
  end

  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "settings", :to => "devise/registrations#edit"
    get "logout",   :to => "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :code_links, dependent: :destroy
  accepts_nested_attributes_for :code_links, :allow_destroy => true,
  reject_if: :reject_links

  def reject_links(attributed)
    attributed['title'].blank? || attributed['link'].blank?
  end

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  validates :title, presence: true
  validates :description, presence: true
  validates :year, presence: true, numericality: { only_integer: true, greater_than: 2012,
  less_than_or_equal_to: Time.now.year }

  Paperclip.interpolates :slug do |attachment, style|
    attachment.instance.slug
  end

  has_attached_file :icon, :styles => { thumb: "200x200#" },
  path: "/projects/:slug/:attachment/:style/:filename",
  url: "/projects/:slug/:attachment/:style/:filename",
  default_url: "/images/projects/:attachment/:style/missing.png"
  include DeletableAttachment
  validates_attachment_content_type :icon, content_type: /\Aimage\/.*\Z/

  def slug_candidates
    [
     :title,
     [:title, :year]
    ]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def show
  end

  # Create a blank project to be used by form.
  def new
    @project = Project.new
  end

  # Push a new project to the database with inputted parameters.
  # If saved successfully redirects to show project, otherwise back to form.
  def create
    @project = Project.new(project_params)
 
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  # Default method for projects. Gives all current projects and alumni.
  def index
    @projects = Project.all.order('title ASC, year')
  end

  # Give project whose ID or slug matches request, to be used by form.
  def edit
  end

  # Find project whose ID or slug matches request, then update parameters
  # to new inputted values. If updates successfully redirects to show project,
  # otherwise back to edit form.
  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  # Erase project from database, then redirect to index page.
  def destroy
    @project.destroy
    
    redirect_to projects_path
  end

  private
  def set_project
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :link, :description, :year, :icon,
                                    :delete_icon, code_links_attributes: [:title, :link,
                                                                          :description,
                                                                          :id, :_destroy])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_bubble.html.haml
.bubble
  = link_to image_tag(project.icon.url(:thumb)), project, class: "img-link"
  = link_to project.title, project

app/views/projects/_code_link_fields.html.haml
.nested-fields.column.small-6
  .row
    .column.small-12
      = f.input :title
    .column.small-12
      = f.input :link
    .column.small-12
      = f.input :description
    = link_to_remove_association "Remove Link", f, class: "column small-12"

app/views/projects/_code_snippets.html.haml
%section.code-snippets
  %h2#snippets-header // Code Snippet
  .default
    <p>Feel free to select a <span>Code Snippet</span> on the left</p> 
  - project.code_links.each do |code_link|
    %article.code-snippet(id="code-snippet-#{code_link.id}")
      %h3(class="code-link")= code_link.title
      .gist(data-src="#{code_link.link}.json")

app/views/projects/_form.html.haml
= simple_form_for @project do |f|
  .row
    .column.small-12
      = f.input :title

    .column.small-12
      = f.input :year

    .column.small-12
      = f.input :link

    .column.small-12
      = f.input :description

    .column.small-7
      = f.input :icon
    .column.small-2
      = f.input :delete_icon, as: :boolean

  %section#nested-fields
    .row
      %h2.column.small-12 Code Links
    #code-links.row
      = f.simple_fields_for :code_links do |code_link|
        = render "code_link_fields", f: code_link
      = link_to_add_association "Add Code Link", f, :code_links, class: "column small-12"

  .row
    .column.small-5
      = f.button :submit, class: "button small"

app/views/projects/_show.html.haml
%article.project
  - if project.link.length > 0
    %h2.title
      = link_to project.title, project.link, target: "_blank", class: "header-link"
  - else
    %h2.title= project.title

  - if user_signed_in?
    .icons.row
      = link_to edit_project_path(project), class: "column small-6" do
        %i.fi-pencil
      = link_to project_path(project), method: :delete, class: "column small-6",
        data: { confirm: "Are you sure you'd like to delete project '#{project.title}'?" } do
        %i.fi-trash

  .description
    :markdown
      #{project.description}

  .snippet-links
    %h2 Code Snippets
    - project.code_links.each do |code_link|
      %article.snippet-link
        = link_to code_link.title, "javascript:void(0)", onclick: "showOnlyOne('code-snippet-#{code_link.id}');", class: "code-link"
        :markdown
          #{code_link.description}

app/views/projects/edit.html.haml
%h1.form-header Editing Project

= render "form"

app/views/projects/index.html.haml
- title = "My Projects"
- description = "Get a quick glance at a few of the projects I've worked on."
- image = URI.join(root_url, image_path("favicon.png"))

- meta title: title, description: description,
  og: { title: title, description: description, image: image, url: request.original_url }

.left
  #project-content
    - @projects.each do |project|
      = render "bubble", project: project

  - if user_signed_in?
    .add-new
      = link_to image_tag("icons/add.png"), new_project_path

.right

app/views/projects/new.html.haml
.row
  %h1.form-header.column.small-12 New Project

= render "form"

app/views/projects/show.html.haml
- title = "#{@project.title} | My Projects"
- description = @project.description
- image = @project.icon.url(:original)

- meta title: title, description: description,
  og: { title: title, description: description, image: image, url: request.original_url }

.left
  = render "show", project: @project

.right
  = render "code_snippets", project: @project