config/routes.rb
Rails.application.routes.draw do

  root 'front_page#main'

  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'resume' => 'pages#resume'

  resources :jobs
  resources :courses
  resources :projects
  resources :code_links

  if Rails.env.production?
    devise_for :users, controllers: { registrations: "registrations" }
  else
    devise_for :users
  end

  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "settings", :to => "devise/registrations#edit"
    get "logout",   :to => "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
  end

end

app/views/layouts/_footer.html.haml
-# %nav.icons
-#   = link_to image_tag("icons/github.png"),
-#     "https://www.github.com/greytoyota", :target => "_blank"
-#   = link_to image_tag("icons/google_plus.png"),
-#     "https://plus.google.com/+JoelGraycar/posts", :target => "_blank"
-#   = link_to image_tag("icons/linkedin.png"),
-#     "http://www.linkedin.com/in/jgraycar", :target => "_blank"

app/views/layouts/_header.html.haml
= link_to "Joel Graycar", root_url, id: "logo-text"
%nav#nav-bar
  .link#projects-page
    %a.main-link PROJECTS
    - projects = Project.all.order('title ASC, year')
    %ul
      - projects.each do |project|
        %li
          = link_to project.title, project
      - if user_signed_in?
        %li
          = link_to "Add Project", new_project_path

  - if user_signed_in?
    .link#courses-page
      = link_to "COURSES", courses_path, class: "main-link"

  .link#resume-page
    = link_to "RESUME", "/resume", class: "main-link"

  .link#about-page
    = link_to "ABOUT", "/about", class: "main-link"

  - if user_signed_in?
    .link
      = link_to "LOGOUT", "/logout", "data-no-turbolink" => true, class: "main-link"

app/views/layouts/application.html.haml
!!!
%html(lang="en-US")
  %head
    %meta(charset="utf-8")
    = metamagic title: "Joel Graycar",
      keywords: "joel, graycar, personal, portfolio"

    %link(href="//brick.a.ssl.fastly.net/Inconsolata:400,500/Lato:400,700" rel="stylesheet" type="text/css")
    %link(href='http://fonts.googleapis.com/css?family=Inconsolata:400,700' rel='stylesheet' type='text/css')

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag :modernizr
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

    = favicon_link_tag "favicon.png", rel: "icon", type: "image/png"
    = favicon_link_tag "favicon.png", rel: "apple-touch-icon", type: "image/png"

    %meta(name="mobile-web-app-capable" content="yes")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

  %body{ class: "#{controller.controller_name}", id: "#{controller.action_name}" }
    %section.spacer
      = link_to image_tag("semi-colon.svg"), root_url, id: "semi-colon"
    %header#nav-header
      = render "layouts/header"

    .devise-notice
      - if notice
        .alert-box.success(data-alert)
          = notice
      - if alert
        .alert-box.alert
          = alert

    = yield